openapi: 3.0.0

info:
  version: 0.0.1
  title: Price Service
  description: Query API that answers the applicable price

tags:
  - name: "Price API"

paths:

  /price:
    get:
      summary: Endpoint that answers the final price to apply
      tags:
        - "Price"
      description: Endpoint description
      operationId: getPrice
      parameters:
        - name: productId
          in: query
          required: true
          schema:
            type: integer
        - name: brandId
          in: query
          required: true
          schema:
            type: integer
        - name: date
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description:  Successful
          content:
            application/json:
              schema:
                type: object
                $ref: '#/components/schemas/PriceDTO'
        "400":
          description: Server can't process the request
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    PriceDTO:
      description: Price model that represents the applicable price during a period of time for a product
      type: object
      properties:
        productId:
          description: Product identifier code
          type: integer
          example: 12345
        brandId:
          description: Foreign key that represents the brand
          type: integer
          example: 1
        priceList:
          description: Identifier of the applicable price list
          type: integer
          example: 1
        startDate:
          description: Beginning of the price validity
          type: string
        endDate:
          description: Ending of the price validity
          type: string
        price:
          description: Final selling price
          type: number
          multipleOf: 0.01
          example: 99.99
        currency:
          description: Currency name as defined on the ISO 4217
          type: string
          pattern: ^[A-Z]{3}$
          example: EUR